services:
  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      args:
        - PORT=8000
    ports:
      - "8000:8000"
    environment:
      - GIN_MODE=release
      - OLLAMA_SCHEME=http
      - OLLAMA_URL=ollama:11434
      - PORT=8000
    depends_on:
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  ollama:
    container_name: ollama
    build:
      context: ./ollama
    pull_policy: always
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_MAX_LOADED_MODELS=2
      - OLLAMA_MODELS=/usr/share/ollama/.ollama/models
    healthcheck:
      test: "ollama --version && ollama ps || exit 1"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ollama-models:/usr/share/ollama/.ollama/models

volumes:
  ollama-models:
